### ISSUE TITLE
Take Valuables button seams to be misplaced

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/SimpleBiggerBackpack#1]
The "Take Valuables" button is located in the middle of the backpack inventory, rather than being positioned at the edge under the "Take All" button.

![image](https://github.com/user-attachments/assets/18b70fbb-a516-46dc-8ae3-96d598fde5e1)

**Comment by altairwei** [comment]
I think "Take Valuables" was introduced by the UI+ mod. Maybe, there is a compatibility problem.

**Comment by TadhgEomonn** [comment]
Should I do something about this? Or will you be communicating with the UI+ mod author?

**Comment by altairwei** [comment]
> Should I do something about this? Or will you be communicating with the UI+ mod author?

Nope. I am uploading "a brand new version" of this mod, and does not exist this problem.

**Comment by TadhgEomonn** [comment]
Understood. Thank you.

**Comment by altairwei** [comment]
@TadhgEomonn I have uploaded a v1.0.1 to solve this issue.
