### ISSUE TITLE
Request: add label to open backpack window

### ISSUE THREAD

**Issue by TadhgEomonn** [altairwei/SimpleBiggerBackpack#2]
When a chest is opened, it has a label.

![image](https://github.com/user-attachments/assets/e512dbe0-613b-4047-8463-e32a46608af0)

If you can, please add a label to the open backpack. This will cut down on the uncertainty of which container is opened. The present backpack has no label.

![image](https://github.com/user-attachments/assets/fc539822-2f03-40b6-9e0c-ed5d376f19c2)

**Comment by altairwei** [comment]
I don't feel it's necessary, because you can't have multiple container windows open at the same time.

**Comment by TadhgEomonn** [comment]
See that you added the labels anyway. I think it is an improvement to the mod. Thanks.
